name: CI-minimal

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ["3.7"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install rubberband-cli and ffmpeg
        run: sudo apt-get update && sudo apt-get install -y rubberband-cli

      - name: Install dependencies
        run: pip install --use-deprecated=legacy-resolver -e .[tests]

      - name: Run test
        run: python -m pytest tests

